apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-micro
spec:
  replicas: 3
  template:
    metadata:
      labels:
        name: node-micro
    spec:
      containers:
      - name: node-micro
        image: gcr.io/loadmill-142315/node-micro:1.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000