apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: node-micro
  namespace: default
spec:
  replicas: 2
  template:
    metadata:
      labels:
        name: node-micro
    spec:
      containers:
      - name: node-micro
        image: gcr.io/loadmill-142315/node-micro:2.0
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 3000
        env:
        - name: LOADMILL_VERIFY_TOKEN
          value: replace-me